# Generated by Django 4.0 on 2022-11-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('note', models.TextField(verbose_name='Текст')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='core.employee', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Заметка по работнику',
                'verbose_name_plural': 'Заметки по работникам',
                'ordering': ('-date', '-pk'),
            },
        ),
    ]
