# Generated by Django 4.0 on 2022-09-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_mar_in_putewka', models.IntegerField(verbose_name='Номер в программе Путевки')),
                ('gos_nom_in_putewka', models.CharField(max_length=4, unique=True, verbose_name='Гос. номер в программе Путевки (PK)')),
                ('state_number', models.CharField(max_length=16, unique=True, verbose_name='Гос. номер')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('kod_driver', models.IntegerField(blank=True, null=True, verbose_name='Код водителя в программе Путевки')),
                ('date_decommissioned', models.DateField(blank=True, null=True, verbose_name='Дата списания')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ('name', 'state_number'),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_kadry', models.IntegerField(unique=True, verbose_name='Номер в программе Кадры')),
                ('first_name', models.CharField(max_length=24, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=24, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=24, verbose_name='Отчество')),
                ('type', models.IntegerField(choices=[(1, 'Водитель'), (2, 'Слесарь'), (3, 'Управление')], verbose_name='Тип')),
                ('position', models.CharField(max_length=32, verbose_name='Должность')),
                ('date_dismissal', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ('type', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
                ('type', models.IntegerField(choices=[(1, 'ТО'), (2, 'Ремонт'), (3, 'Прочее')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Причина',
                'verbose_name_plural': 'Причины',
                'ordering': ('type', 'name'),
            },
        ),
    ]
