# Generated by Django 4.0 on 2022-10-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('status', models.IntegerField(choices=[(1, 'Заяка'), (2, 'В работе'), (3, 'Выполнен')], verbose_name='Статус')),
                ('date_begin', models.DateTimeField(verbose_name='Дата и время начала работ')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения работ')),
                ('odometer', models.IntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.car', verbose_name='ТС')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'type': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_from_driver', to='core.employee', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Заказ-наряд',
                'verbose_name_plural': 'Заказ-наряды',
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='OrderWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('time_minutes', models.IntegerField(blank=True, null=True, verbose_name='Затрачено времени, мин')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_works', to='orders.order', verbose_name='Заказ-наряд')),
            ],
            options={
                'verbose_name': 'Работа в заказ-наряде',
                'verbose_name_plural': 'Работы в заказ-наряде',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
                ('type', models.IntegerField(choices=[(1, 'ТО'), (2, 'Ремонт'), (3, 'Прочее')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Причина',
                'verbose_name_plural': 'Причины',
                'ordering': ('type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Наименование')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='orders.workcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrderWorkMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_minutes', models.IntegerField(blank=True, null=True, verbose_name='Затрачено времени, мин')),
                ('mechanic', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='order_works', to='core.employee', verbose_name='Слесарь')),
                ('order_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='orders.orderwork', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Работа слесарей в заказ-наряде',
                'verbose_name_plural': 'Работы слесарей в заказ-наряде',
            },
        ),
        migrations.AddField(
            model_name='orderwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_works', to='orders.work', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='order',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.post', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.reason', verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='order',
            name='responsible',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_from_responsible', to='core.employee', verbose_name='Ответсвенный'),
        ),
    ]
