# Generated by Django 4.0 on 2022-11-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customgroup_options_alter_customuser_groups_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='authentication.customuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
