# Generated by Django 4.0 on 2022-11-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Наименование'),
        ),
    ]
