# Generated by Django 4.0 on 2022-11-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0003_alter_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderworkmechanic',
            name='mechanic',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', 2), ('type', 1), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='order_works', to='core.employee', verbose_name='Слесарь'),
        ),
    ]
