# Generated by Django 4.0 on 2023-02-08 04:45

from django.db import migrations


def make_many_reasons(apps, schema_editor):
    """
        Adds the Reason object in Order.reason to the
        many-to-many relationship in Order.reasons
    """
    Order = apps.get_model('orders', 'Order')

    for order in Order.objects.all():
        order.reasons.add(order.reason)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_reasons_alter_order_reason'),
    ]

    operations = [
        migrations.RunPython(make_many_reasons),
    ]
