# Generated by Django 4.0 on 2023-02-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20230208_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reason',
        ),
    ]
