# Generated by Django 4.0 on 2023-01-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_order_car'),
        ('core', '0001_initial'),
        ('authentication', '0002_alter_customgroup_options_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('materials', models.TextField(blank=True, verbose_name='Необходимые материалы')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.car', verbose_name='ТС')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_from_order', to='orders.order', verbose_name='Заказ-наряд')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='authentication.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('-created', 'pk'),
            },
        ),
    ]
